NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.fundinc.fund.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.fundinc.fund.com-cert.pem
    OrganizationalUnitIdentifier: peer
