# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.fund.com:
    container_name: orderer.fund.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/fund.com/orderers/orderer.fund.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/fund.com/orderers/orderer.fund.com/tls/:/var/hyperledger/orderer/tls
    - ../prod/orderer.fund.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - byfn

  peer0.maple.fund.com:
    container_name: peer0.maple.fund.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.maple.fund.com
      - CORE_PEER_ADDRESS=peer0.maple.fund.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.maple.fund.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.maple.fund.com:7051
      - CORE_PEER_LOCALMSPID=maple
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/maple.fund.com/peers/peer0.maple.fund.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/maple.fund.com/peers/peer0.maple.fund.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer0.maple.fund.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.maple.fund.com:
    container_name: peer1.maple.fund.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.maple.fund.com
      - CORE_PEER_ADDRESS=peer1.maple.fund.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.maple.fund.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.maple.fund.com:7051
      - CORE_PEER_LOCALMSPID=maple
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/maple.fund.com/peers/peer1.maple.fund.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/maple.fund.com/peers/peer1.maple.fund.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer1.maple.fund.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.fundinc.fund.com:
    container_name: peer0.fundinc.fund.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
      - CORE_PEER_ID=peer0.fundinc.fund.com
      - CORE_PEER_ADDRESS=peer0.fundinc.fund.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fundinc.fund.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.fundinc.fund.com:7051
      - CORE_PEER_LOCALMSPID=fundinc
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fundinc.fund.com/peers/peer0.fundinc.fund.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fundinc.fund.com/peers/peer0.fundinc.fund.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer0.fundinc.fund.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.fundinc.fund.com:
    container_name: peer1.fundinc.fund.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.fundinc.fund.com
      - CORE_PEER_ADDRESS=peer1.fundinc.fund.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fundinc.fund.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fundinc.fund.com:7051
      - CORE_PEER_LOCALMSPID=fundinc
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fundinc.fund.com/peers/peer1.fundinc.fund.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fundinc.fund.com/peers/peer1.fundinc.fund.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer1.fundinc.fund.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
